database = {
    "Users": [
        {
            "User_id": 1,
            "Password": "hashed_password_123",
            "Name": "John",
            "Surname": "Doe",
            "Email": "john@example.com",
            "Role": "coordinator",
            "Phone_number": "+123456789",
            "DOB": "1990-01-01 00:00:00",
            "Created_At": "2023-01-01 10:00:00",
            "Updated_At": "2023-01-01 10:00:00",
            "Is_Active": True,
            "On_Call": True,
            "Avg_Response_Time_Mins": 15,
        },
        {
            "User_id": 2,
            "Password": "hashed_password_456",
            "Name": "Jane",
            "Surname": "Smith",
            "Email": "jane@example.com",
            "Role": "volunteer",
            "Phone_number": "+987654321",
            "DOB": "1995-05-12 00:00:00",
            "Created_At": "2023-02-15 12:00:00",
            "Updated_At": "2023-02-15 12:00:00",
            "Is_Active": True,
            "On_Call": True,
            "Avg_Response_Time_Mins": 8,
        },
        {
            "User_id": 3,
            "Password": "hashed_password_789",
            "Name": "Sam",
            "Surname": "Manager",
            "Email": "manager@example.com",
            "Role": "system_manager",
            "Phone_number": "+44123456789",
            "DOB": "1985-03-20 00:00:00",
            "Created_At": "2023-01-01 09:00:00",
            "Updated_At": "2023-01-01 09:00:00",
            "Is_Active": True,
            "On_Call": False,
            "Avg_Response_Time_Mins": 0,
        },
    ],
    "Skills": [
        {
            "skills_id": 501,
            "Title": "First Aid",
            "description": "Basic life support",
            "skills": "Medical",
            "Skills_description": None,
            "Certified": "Yes",
            "reliability": "Trustworthy",
            "Proof_of_Certificate": "cert_url_001",
            "Certificate_name": "Red Cross Cert",
            "ExpirationDate_certificate": "2025-12-31 23:59:59",
            "Course_taken_at": "2022-05-01 00:00:00",
        }
    ],
    "Volunteer_skills": [
        {
            "id": 1,
            "Skills_id": 501,
            "User_id": 2,
        }
    ],
    "Incidents": [
        {
            "Incident_id": 101,
            "Title": "Flood in Sector 7",
            "Description": "Heavy rainfall causing flooding in residential area.",
            "Type": "Flood",
            "Latitude": 40.7128,
            "Longitude": -74.0060,
            "Priority": "urgent",
            "Volunteers_helped": 5,
            "Created_at": "2023-10-27 08:00:00",
            "Created_by": 1,
            "Ended_at": None,
            "Ended_by": None,
            "Is_Project": True,
            "Project_Name": "Autumn Flood Relief",
        },
        {
            "Incident_id": 102,
            "Title": "Power Outage",
            "Description": "Main grid down in downtown.",
            "Type": "Other",
            "Latitude": 40.7306,
            "Longitude": -73.9352,
            "Priority": "medium",
            "Volunteers_helped": 0,
            "Created_at": "2023-10-27 09:30:00",
            "Created_by": 1,
            "Ended_at": "2023-10-27 11:00:00",
            "Ended_by": 1,
            "Is_Project": False,
            "Project_Name": None,
        },
        {
    "Incident_id": 103,
    "Title": "Wildfire Near Pine Hills",
    "Description": "Rapidly spreading wildfire threatening nearby homes.",
    "Type": "Fire",
    "Latitude": 34.0522,
    "Longitude": -118.2437,
    "Priority": "urgent",
    "Volunteers_helped": 12,
    "Created_at": "2023-10-28 07:15:00",
    "Created_by": 2,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Pine Hills Fire Response",
},
{
    "Incident_id": 104,
    "Title": "Road Accident on Highway 12",
    "Description": "Multi-vehicle collision causing traffic disruption.",
    "Type": "Accident",
    "Latitude": 41.8781,
    "Longitude": -87.6298,
    "Priority": "high",
    "Volunteers_helped": 3,
    "Created_at": "2023-10-28 10:20:00",
    "Created_by": 3,
    "Ended_at": "2023-10-28 13:45:00",
    "Ended_by": 2,
    "Is_Project": False,
    "Project_Name": None,
},
{
    "Incident_id": 105,
    "Title": "Community Food Shortage",
    "Description": "Local shelter requires food supplies for displaced families.",
    "Type": "Relief",
    "Latitude": 29.7604,
    "Longitude": -95.3698,
    "Priority": "medium",
    "Volunteers_helped": 8,
    "Created_at": "2023-10-29 09:00:00",
    "Created_by": 2,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Food Assistance Drive",
},
{
    "Incident_id": 106,
    "Title": "Earthquake Damage Assessment",
    "Description": "Teams needed to assess structural damage after tremors.",
    "Type": "Earthquake",
    "Latitude": 37.7749,
    "Longitude": -122.4194,
    "Priority": "urgent",
    "Volunteers_helped": 15,
    "Created_at": "2023-10-30 06:45:00",
    "Created_by": 4,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Earthquake Recovery Initiative",
},
{
    "Incident_id": 107,
    "Title": "Medical Emergency Camp",
    "Description": "Temporary medical camp needed due to disease outbreak.",
    "Type": "Medical",
    "Latitude": 51.5074,
    "Longitude": -0.1278,
    "Priority": "high",
    "Volunteers_helped": 10,
    "Created_at": "2023-10-31 08:30:00",
    "Created_by": 3,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Health Response Program",
},
{
    "Incident_id": 108,
    "Title": "Water Supply Disruption",
    "Description": "Major pipeline failure affecting several neighborhoods.",
    "Type": "Infrastructure",
    "Latitude": 48.8566,
    "Longitude": 2.3522,
    "Priority": "medium",
    "Volunteers_helped": 2,
    "Created_at": "2023-11-01 11:10:00",
    "Created_by": 1,
    "Ended_at": "2023-11-01 18:00:00",
    "Ended_by": 1,
    "Is_Project": False,
    "Project_Name": None,
},
{
    "Incident_id": 109,
    "Title": "Severe Storm Warning",
    "Description": "Strong winds and heavy rain expected across the region.",
    "Type": "Storm",
    "Latitude": 35.6895,
    "Longitude": 139.6917,
    "Priority": "high",
    "Volunteers_helped": 6,
    "Created_at": "2023-11-02 05:20:00",
    "Created_by": 5,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Storm Preparedness Campaign",
},
{
    "Incident_id": 110,
    "Title": "Search and Rescue Operation",
    "Description": "Missing hikers reported in mountainous terrain.",
    "Type": "Rescue",
    "Latitude": 39.7392,
    "Longitude": -104.9903,
    "Priority": "urgent",
    "Volunteers_helped": 20,
    "Created_at": "2023-11-03 14:00:00",
    "Created_by": 4,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Mountain Rescue Mission",
},
{
    "Incident_id": 111,
    "Title": "Landslide Blocking Access Road",
    "Description": "Landslide has cut off access to a rural community.",
    "Type": "Landslide",
    "Latitude": 27.7172,
    "Longitude": 85.3240,
    "Priority": "high",
    "Volunteers_helped": 7,
    "Created_at": "2023-11-04 07:50:00",
    "Created_by": 2,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Rural Access Restoration",
},
{
    "Incident_id": 112,
    "Title": "Shelter Support Needed",
    "Description": "Emergency shelter requires volunteers and supplies.",
    "Type": "Relief",
    "Latitude": 52.5200,
    "Longitude": 13.4050,
    "Priority": "medium",
    "Volunteers_helped": 9,
    "Created_at": "2023-11-05 12:25:00",
    "Created_by": 5,
    "Ended_at": None,
    "Ended_by": None,
    "Is_Project": True,
    "Project_Name": "Winter Shelter Assistance",
},
    ],
    "Volunteer_help": [
        {
            "id": 1001,
            "User_id": 2,
            "Incident_id": 101,
            "Created_at": "2023-10-27 08:15:00",
            "Update_at": "2023-10-27 08:15:00",
            "Ended_at": "2023-10-27 10:00:00",
            "Response_Time_Seconds": 900,
        }
    ],
    "Team": [
        {
            "team_id": 1,
            "incident_id": 101,
            "Coordinator_id": 1,
            "Team_leader_id": 2,
            "Name": "Flood Response Team A",
            "Task": "Distribute water and blankets",
        }
    ],
    "Teams_": [
        {
            "Team_id": 1,
            "User_id": 2,
        }
    ],
}
