database = {
    "Users": [
        {
            "User_id": 1,
            "Password": "hashed_password_123",
            "Name": "John",
            "Surname": "Doe",
            "Email": "john@example.com",
            "Role": "coordinator",
            "Phone_number": "+123456789",
            "DOB": "1990-01-01 00:00:00",
            "Created_At": "2023-01-01 10:00:00",
            "Updated_At": "2023-01-01 10:00:00",
            "Is_Active": True,
            "On_Call": True,
            "Avg_Response_Time_Mins": 15,
        },
        {
            "User_id": 2,
            "Password": "hashed_password_456",
            "Name": "Jane",
            "Surname": "Smith",
            "Email": "jane@example.com",
            "Role": "volunteer",
            "Phone_number": "+987654321",
            "DOB": "1995-05-12 00:00:00",
            "Created_At": "2023-02-15 12:00:00",
            "Updated_At": "2023-02-15 12:00:00",
            "Is_Active": True,
            "On_Call": True,
            "Avg_Response_Time_Mins": 8,
        },
        {
            "User_id": 3,
            "Password": "hashed_password_789",
            "Name": "Sam",
            "Surname": "Manager",
            "Email": "manager@example.com",
            "Role": "system_manager",
            "Phone_number": "+44123456789",
            "DOB": "1985-03-20 00:00:00",
            "Created_At": "2023-01-01 09:00:00",
            "Updated_At": "2023-01-01 09:00:00",
            "Is_Active": True,
            "On_Call": False,
            "Avg_Response_Time_Mins": 0,
        },
    ],
    "Skills": [
        {
            "skills_id": 501,
            "Title": "First Aid",
            "description": "Basic life support",
            "skills": "Medical",
            "Skills_description": None,
            "Certified": "Yes",
            "reliability": "Trustworthy",
            "Proof_of_Certificate": "cert_url_001",
            "Certificate_name": "Red Cross Cert",
            "ExpirationDate_certificate": "2025-12-31 23:59:59",
            "Course_taken_at": "2022-05-01 00:00:00",
        }
    ],
    "Volunteer_skills": [
        {
            "id": 1,
            "Skills_id": 501,
            "User_id": 2,
        }
    ],
    "Incidents": [
        {
            "Incident_id": 101,
            "Title": "Flood in Sector 7",
            "Description": "Heavy rainfall causing flooding in residential area.",
            "Type": "Flood",
            "Latitude": 40.7128,
            "Longitude": -74.0060,
            "Priority": "Urgent",
            "Volunteers_helped": 5,
            "Created_at": "2023-10-27 08:00:00",
            "Created_by": 1,
            "Ended_at": None,
            "Ended_by": None,
            "Is_Project": True,
            "Project_Name": "Autumn Flood Relief",
        },
        {
            "Incident_id": 102,
            "Title": "Power Outage",
            "Description": "Main grid down in downtown.",
            "Type": "Other",
            "Latitude": 40.7306,
            "Longitude": -73.9352,
            "Priority": "Medium",
            "Volunteers_helped": 0,
            "Created_at": "2023-10-27 09:30:00",
            "Created_by": 1,
            "Ended_at": "2023-10-27 11:00:00",
            "Ended_by": 1,
            "Is_Project": False,
            "Project_Name": None,
        },
    ],
    "Volunteer_help": [
        {
            "id": 1001,
            "User_id": 2,
            "Incident_id": 101,
            "Created_at": "2023-10-27 08:15:00",
            "Update_at": "2023-10-27 08:15:00",
            "Ended_at": "2023-10-27 10:00:00",
            "Response_Time_Seconds": 900,
        }
    ],
    "Team": [
        {
            "team_id": 1,
            "incident_id": 101,
            "Coordinator_id": 1,
            "Team_leader_id": 2,
            "Name": "Flood Response Team A",
            "Task": "Distribute water and blankets",
        }
    ],
    "Teams_": [
        {
            "Team_id": 1,
            "User_id": 2,
        }
    ],
}
